# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-14 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20170513_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='remotehost',
            name='supervisor_project_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='command',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='job',
            name='item',
            field=models.CharField(default='', max_length=45),
        ),
        migrations.AlterField(
            model_name='job',
            name='item_path',
            field=models.CharField(default='', max_length=45),
        ),
        migrations.AlterField(
            model_name='jobmessage',
            name='message',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='remote',
            name='port',
            field=models.IntegerField(default=22),
        ),
        migrations.AlterField(
            model_name='remotehost',
            name='alias_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='remotehost',
            name='hostname',
            field=models.CharField(default='', max_length=45),
        ),
    ]
