# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-14 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20170514_1341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remotehost',
            name='supervisor_project_name',
        ),
        migrations.AddField(
            model_name='remotehost',
            name='supervisor_project',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
