# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-14 23:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0006_auto_20170514_2335'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobname', models.CharField(max_length=45)),
                ('command', models.CharField(default='', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='JobMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(default='', max_length=100)),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Job')),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=45)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('last_login_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Remote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('ip', models.CharField(default='', max_length=100)),
                ('host', models.CharField(default='', max_length=100)),
                ('user', models.CharField(default='', max_length=45)),
                ('port', models.IntegerField(default=22)),
                ('default_path', models.CharField(default='', max_length=200)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SupervisorHost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('ip', models.CharField(max_length=45)),
                ('hostname', models.CharField(default='', max_length=45)),
                ('supervisor_project', models.CharField(default='', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssh_key_path', models.CharField(default='/root/.ssh/id_rsa', max_length=100)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='login',
            unique_together=set([('username', 'password')]),
        ),
        migrations.AddField(
            model_name='job',
            name='remote_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Remote'),
        ),
    ]
