# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 18:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20170515_0718'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supervisorhost',
            old_name='ip',
            new_name='host',
        ),
    ]
