# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 21:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20170606_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisorhost',
            name='display',
            field=models.IntegerField(choices=[(0, 'undisplay'), (1, 'display')], default=0, max_length=2),
        ),
    ]
