# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 21:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20170606_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supervisorhost',
            name='display',
            field=models.CharField(choices=[('0', 'undisplay'), ('1', 'display')], default='1', max_length=2),
        ),
    ]
