# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-08 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20170607_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisorhost',
            name='is_group',
            field=models.CharField(choices=[('0', 'process'), ('1', 'group')], db_index=True, default='0', max_length=2),
        ),
        migrations.AlterField(
            model_name='supervisorhost',
            name='display',
            field=models.CharField(choices=[('0', 'undisplay'), ('1', 'display')], db_index=True, default='1', max_length=2),
        ),
    ]
