# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-11 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20170608_1757'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrontabHost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=100)),
                ('cron_user', models.CharField(blank='', max_length=100)),
                ('cron', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
