# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-11 21:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_crontabhost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crontabhost',
            old_name='host',
            new_name='cron_host',
        ),
        migrations.RenameField(
            model_name='crontabhost',
            old_name='cron',
            new_name='crontab',
        ),
        migrations.AddField(
            model_name='crontabhost',
            name='cron_display',
            field=models.CharField(choices=[('0', 'undisplay'), ('1', 'display')], db_index=True, default='1', max_length=2),
        ),
        migrations.AddField(
            model_name='crontabhost',
            name='describe',
            field=models.TextField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='crontabhost',
            name='name',
            field=models.CharField(default='空', max_length=100),
        ),
    ]
